server:
  port: 8080
  error:
    whitelable:
      enabled: false
      spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/lutiy-project
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
