package ru.CheSeVe.lutiy_project.enums;



public enum Hero {
    ABADDON, ALCHEMIST, AXE, BEASTMASTER, BREWMASTER, BRISTLEBACK, CENTAUR_WARRUNNER, CHAOS_KNIGHT, CLOCKWERK,
    DAWNBREAKER, DOOM, DRAGON_KNIGHT, EARTH_SPIRIT, EARTHSHAKER, ELDER_TITAN, HUSKAR, IO, KUNKKA, LEGION_COMMANDER,
    LIFESTEALER, LYCAN, MAGNUS, MARS, NIGHT_STALKER, OMNIKNIGHT, PHOENIX, PRIMAL_BEAST, PUDGE, SAND_KING, SLARDAR,
    SNAPFIRE, SPIRIT_BREAKER, SVEN, TIDEHUNTER, TIMBERSAW, TINY, TREANT_PROTECTOR, TUSK, UNDERLORD, UNDYING, WRAITH_KING,

    ANTI_MAGE, ARC_WARDEN, BLOODSEEKER, BOUNTY_HUNTER, BROODMOTHER, CLINKZ, DROW_RANGER, EMBER_SPIRIT, FACELESS_VOID,
    GYROCOPTER, HOODWINK, JUGGERNAUT, KEZ, LONE_DRUID, LUNA, MEDUSA, MEEPO, MIRANA, MONEKY_KING, MORPHLING, NAGA_SIREN,
    NYX_ASSASSIN, PANGOLIER, PHANTOM_ASSASSIN, PHANTOM_LANCER, RAZOR, RIKI, SHADOW_FIEND, SLARK, SNIPER, SPECTRE,
    TEMPLAR_ASSASSIN, TERRORBLADE, TROLL_WARLORD, URSA, VENGEFUL_SPIRIT, VENOMANCER, VIPER, WEAVER,

    ANCIENT_APPARITION, BANE, BATRIDER, CHEN, CRYSTAL_MAIDEN, DARK_SEER, DARK_WILLOW, DAZZLE, DEATH_PROPHET, DISRUPTOR,
    ENCHANTRESS, ENIGMA, GRIMSTROKE, INVOKER, JAKIRO, KEEPER_OF_THE_LIGHT, LESHRAC, LICH, LINA, LION, NATURES_PROPHET,
    NECROPHOS, OGRE_MAGI, ORACLE, OUTWORLD_DESTROYER, PUCK, PUGNA, QUEEN_OF_PAIN, RINGMASTER, RUBICK, SHADOW_DEMON,
    SHADOW_SHAMAN,SILENCER, SKYWRATH_MAGE, STORM_SPIRIT, TECHIES, TINKER, VISAGE, VOID_SPIRIT, WARLOCK, WINDRANGER,
    WINTER_WYVERN, WITCH_DOCTOR, ZEUS




}
