package ru.CheSeVe.lutiy_project.enums;





public enum Item {
    ABYSSAL_BLADE, AEGIS_OF_THE_IMMORTAL, AEON_DISK, AETHER_LENS, AGHANIMS_BLESSING, AGHANIMS_SCEPTER, AGHANIMS_SHARD,
ARCANE_BLINK, ARCANE_BOOTS, ARMLET_OF_MORDIGGIAN, ASSAULT_CUIRASS, BAND_OF_ELVENSKIN, BATTLE_FURY, 	BELT_OF_STRENGTH,
BLACK_GRIMOIRE, BLACK_KING_BAR, BLADE_MAIL, BLADE_OF_ALACRITY, 	BLADES_OF_ATTACK, BLINK_DAGGER, BLITZ_KNUCKLES,
BLOCK_OF_CHEESE, BLOOD_GRENADE, BLOODSTONE, BLOODTHORN, BOOTS_OF_BEARING, BOOTS_OF_SPEED, BOOTS_OF_TRAVEL,
BOOTS_OF_TRAVEL_2, BOTTLE, BRACER, BROADSWORD, BUCKLER, BUTTERFLY, CHAINMAIL, CHEESE, CIRCLET, CLARITY, CLAYMORE,
CLOAK, CORNUCOPIA, CRIMSON_GUARD, CROWN, CRYSTALYS, DAEDALUS, DAGON, DAGON_LEVEL_2, DAGON_LEVEL_3,
DAGON_LEVEL_4, DAGON_LEVEL_5, DEMON_EDGE, DESOLATOR, DIADEM, DIFFUSAL_BLADE, DISPERSER, DIVINE_RAPIER, DRAGON_LANCE,
DRUM_OF_ENDURANCE, DUST_OF_APPEARANCE, EAGLESONG, ECHO_SABRE, ENCHANTED_MANGO, 	ENERGY_BOOSTER, ETERNAL_SHROUD,
ETHEREAL_BLADE, EULS_SCEPTER_OF_DIVINITY, EYE_OF_SKADI, FAERIE_FIRE, FALCON_BLADE, FLUFFY_HAT, FORCE_STAFF,
GAUNTLETS_OF_STRENGTH, GEM_OF_TRUE_SIGHT, GHOST_SCEPTER, GLEIPNIR, GLIMMER_CAPE, GLOVES_OF_HASTE, GREAT_HEALING_LOTUS,
GREATER_HEALING_LOTUS, GRIS_GRIS, GUARDIAN_GREAVES, HAND_OF_MIDAS, HARPOON, HEADDRESS, HEALING_LOTUS, HEALING_SALVE,
HEART_OF_TARRASQUE, HEAVENS_HALBERD, HELM_OF_IRON_WILL, HELM_OF_THE_DOMINATOR, HELM_OF_THE_OVERLORD, HOLY_LOCKET,
HURRICANE_PIKE, HYPERSTONE, INFUSED_RAINDROPS, IRON_BRANCH, JAVELIN, KAYA, KAYA_AND_SANGE, KHANDA, LINKENS_SPHERE,
LOTUS_ORB, MAELSTROM, MAGE_SLAYER, MAGIC_STICK, MAGIC_WAND, MANTA_STYLE, MANTLE_OF_INTELLIGENCE, MASK_OF_MADNESS,
MEKANSM, METEOR_HAMMER, MITHRIL_HAMMER, MJOLLNIR, MONKEY_KING_BAR, MOON_SHARD, MORBID_MASK, MYSTIC_STAFF,
NULL_TALISMAN, NULLIFIER, OBLIVION_STAFF, OBSERVER_AND_SENTRY_WARDS, OBSERVER_WARD, OCTARINE_CORE, OGRE_AXE,
ORB_OF_BLIGHT, ORB_OF_CORROSION, ORB_OF_FROST, ORB_OF_VENOM, ORCHID_MALEVOLENCE, OVERWHELMING_BLINK, PARASMA,
PAVISE, PERSEVERANCE, PHASE_BOOTS, PHYLACTERY, PIPE_OF_INSIGHT, PLATEMAILM, POINT_BOOSTER, POWER_TREADS, QUELLING_BLADE,
RADIANCE, REAVER, REFRESHER_ORB, REFRESHER_SHARD, REVENANTS_BROOCH, RING_OF_BASILIUS, RING_OF_HEALTH, 	RING_OF_PROTECTION,
RING_OF_REGEN, RING_OF_TARRASQUE, ROBE_OF_THE_MAGI, ROD_OF_ATOS, ROSHANS_BANNER, SACRED_RELIC, SAGES_MASK, SANGE,
SANGE_AND_YASHA, SATANIC, SCYTHE_OF_VYSE, SENTRY_WARD, SHADOW_AMULET, SHADOW_BLADE, SHIVAS_GUARD, SILVER_EDGE,
SKULL_BASHER, SLIPPERS_OF_AGILITY, SMOKE_OF_DECEIT, SOLAR_CREST, SOUL_BOOSTER, SOUL_RING, SPIRIT_VESSEL, STAFF_OF_WIZARDRY,
SWIFT_BLINK, TALISMAN_OF_EVASION, TANGO, TANGO_SHARED, TIARA_OF_SELEMENE, TOWN_PORTAL_SCROLL, TRANQUIL_BOOTS,
ULTIMATE_ORB, URN_OF_SHADOWS, VANGUARD, VEIL_OF_DISCORD, VITALITY_BOOSTER, VLADMIRS_OFFERING, VOID_STONE,
VOODOO_MASK, WIND_LACE, WIND_WAKER, WITCH_BLADE, WRAITH_BAND, YASHA, YASHA_AND_KAYA
}
